name: 'Setup licensee/licensed'
description: 'Setup licensee/licensed for use in GitHub Actions workflows'
branding:
  icon: check
  color: green
inputs:
  github_token:
    description: 'Authentication token to use with the GitHub API'
    required: false
  version:
    description: 'The licensee/licensed version to install'
    required: true
  install-dir:
    description: 'The target install directory for the licensee/licensed executable'
    default: '/usr/local/bin'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
