name: 'Setup github/licensed'
description: 'Setup github/licensed for use in GitHub Actions workflows'
branding:
  icon: check
  color: green
inputs:
  github_token:
    description: 'Authentication token to use with the GitHub API'
    required: false
  version:
    description: 'The github/licensed version to install'
    required: true
  install-dir:
    description: 'The target install directory for the github/licensed executable'
    default: '/usr/local/bin'
    required: false
runs:
  using: 'node12'
  main: 'lib/index.js'
